// Wire Transfer Styles - Extracted for performance
export const getWireTransferStyles = () => ({
  container: {
    minHeight: '100vh',
    backgroundColor: '#0a1f44',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    overflowX: 'hidden',
  },
  mainContent: {
    maxWidth: '1400px',
    marginLeft: 'auto',
    marginRight: 'auto',
    padding: '2rem 1rem',
  },
  card: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '2rem',
    boxShadow: '0 10px 40px rgba(0,0,0,0.1)',
    marginBottom: '2rem',
  },
  button: {
    padding: '1rem 2rem',
    border: 'none',
    borderRadius: '12px',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  receiptModal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(26, 54, 93, 0.95)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10000,
    padding: '1rem',
  },
  receipt: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '2rem',
    maxWidth: '600px',
    maxHeight: '90vh',
    overflowY: 'auto',
    boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
  },
  receiptHeader: {
    textAlign: 'center',
    marginBottom: '2rem',
    paddingBottom: '1rem',
    borderBottom: '2px solid #e2e8f0',
  },
  receiptTitle: {
    fontSize: '1.5rem',
    fontWeight: '700',
    color: '#1a365d',
  },
  receiptRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 0',
    borderBottom: '1px solid #f0f0f0',
  },
  receiptLabel: {
    fontSize: '0.875rem',
    color: '#64748b',
    fontWeight: '600',
  },
  receiptValue: {
    fontSize: '0.875rem',
    color: '#1e293b',
    fontWeight: '600',
    textAlign: 'right',
  },
  receiptButtons: {
    display: 'flex',
    gap: '1rem',
    marginTop: '2rem',
  },
  receiptButton: {
    flex: 1,
    padding: '1rem',
    border: 'none',
    borderRadius: '12px',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  transferItem: {
    padding: '1rem',
    border: '1px solid #e2e8f0',
    borderRadius: '12px',
    marginBottom: '1rem',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  transferItemHover: {
    boxShadow: '0 5px 20px rgba(0,0,0,0.1)',
  },
  transferHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  transferRecipient: {
    fontSize: '1rem',
    fontWeight: '700',
    color: '#1a365d',
    marginBottom: '0.5rem',
  },
  transferDetails: {
    fontSize: '0.875rem',
    color: '#64748b',
    marginBottom: '0.25rem',
  },
  transferAmount: {
    fontSize: '1.25rem',
    fontWeight: '700',
    color: '#059669',
    marginBottom: '0.5rem',
  },
  transferStatus: {
    fontSize: '0.75rem',
    fontWeight: '600',
    padding: '0.25rem 0.75rem',
    borderRadius: '8px',
    color: 'white',
  },
});
